name: Flutter CI/CD - Diawi + TestApp

on:
  push:
    branches: [ main ]

jobs:
  build-and-distribute:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release -t lib/main_prod.dart

      - name: Upload APK to Diawi
        run: |
          curl -F "file=@build/app/outputs/flutter-apk/app-prod-release.apk" \
               -F "token=${{ secrets.DIAWI_TOKEN }}" \
               https://upload.diawi.com/
      
      - name: Upload APK to TestApp.io
        run: |
          curl -X POST https://api.testapp.io/v1/apps/${{ secrets.TESTAPP_APP_ID }}/releases \
          -H "Authorization: Bearer ${{ secrets.TESTAPP_API_KEY }}" \
          -F "file=@build/app/outputs/flutter-apk/app-prod-release.apk"
